default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  username: <%= ENV['POSTGRES_USERNAME'] %>
  password: <%= ENV['POSTGRES_PASSWORD'] %>
  host: localhost

development:
  <<: *default
  database: coffee_shop_development

test:
  <<: *default
  database: coffee_shop_test

production:
  <<: *default
  database: coffee_shop_production
  username: coffee_shop
  password: <%= ENV['COFFEE_SHOP_DATABASE_PASSWORD'] %>